### PR TITLE
Merge from /tg/ [IDB IGNORE] [MDB IGNORE]

### PR DESCRIPTION
**Pull request by MisterBones2910**
### Merge from /tg/. 
There's some good shit in there, bugfixes, yuge debridement buff, etc.

### To do:

1. Ensure this doesn't break any of our shit, obviously
2. Check all the commits as preview only shows 250 most recent
3. Change nerf to shield projector by giving it a cooldown rather than making it take time to project one; should allow for getaway and blocking use while limiting its viability as an offensive trap device as intended in the /tg/ nerf 
4. Add minor mood and flavour text addiction to new cannabis

### CODE REVIEW

**Comment by AffectedArc07** [comment]
Please put `[IDB IGNORE] [MDB IGNORE]` to avoid the diffbots processing this PR, or your repo will be blacklisted

**Comment by AffectedArc07** [comment]
Your repository has been blacklisted.

**Comment by TheChosenEvilOne** [comment]
@AffectedArc07 oops, sorry. We didn't check the comments on this PR and kind of started to wonder why the repo got blacklisted without realising it was this.

**Comment by TheChosenEvilOne** [comment]
We are not going to do it like this.

**Pull request closed without merging**
