### PR TITLE
Re-adds the warden's combat shotgun.

### PR DESCRIPTION
**Pull request by AcapitalA**
**That's right, the warden now has his combat shotgun back!**
**You can find it in the usual spot, the warden's locker.**

The internal magazine now spawns with rubbershot instead of buckshot to be _in-line with the rest of the shotties._

:cl:
add: The warden now has his trusty combat shotgun back.
balance: The shotgun now comes pre-loaded with rubbershot.
/:cl:

### CODE REVIEW

**Comment by Rowelll** [comment]
speedmerge

**Comment by TheChosenEvilOne** [comment]
> speedmerge

I am afraid this is not possible until the last /tg/ upstream merge. I don't want to make the job worse for Edge.

**Comment by TheChosenEvilOne** [comment]
conflict

**Comment by TheChosenEvilOne** [comment]
wrong label, oops.

**Pull request merged**
